services:
  rest-service:
    build: ./app-rest
    container_name: rest-container
    ports:
      - "8081:8080"

  jsf-service:
    build: ./app-jsf
    container_name: jsf-container
    ports:
      - "8080:8080"
    depends_on:
      - [cite_start]rest-service